cocoa-official/CoCoALib

doc/txt/00INTRODUCTION.txt, doc/txt/DenseMatrix.txt, doc/txt/FractionField.txt, doc/txt/HomomorphismOps.txt, doc/txt/MatrixForOrdering.txt, doc/txt/OrthogonalPolys.txt, doc/txt/PBMill.txt, doc/txt/RingHom.txt, doc/txt/factorization.txt
=> a few more typos fixed in doc

doc/CoCoALib-tasks/tasks.xml, doc/txt/DynamicBitset.txt, doc/txt/JBMill.txt, doc/txt/PBMill.txt, examples/ex-QuotientBasis.C, include/CoCoA/convert.H, include/CoCoA/error.H, src/AlgebraicCore/MatrixSpecial.C, src/CoCoA-5/CoCoAManual/CoCoAHelp.xml, src/CoCoA-5/tests/TutHokkaido5.cocoa5
Only real change is making `RandomUnimodularMat` interruptible.
=> RandomUnimodularMat is now interruptible; fixed some typos/grammar; folded some long lines

.gitignore, src/AlgebraicCore/MatrixSpecial.C, src/CoCoA-5/BuiltInFunctions-CoCoALib.C
=> Makefile_depenecies are now ignore; other minor changes

src/AlgebraicCore/MatrixOps-arith.C
Checks once per row -- should be often enough.
=> Made scalar-matrix mult interruptible

.gitignore, src/AlgebraicCore/DenseUPolyRing.C, src/AlgebraicCore/MatrixView.C, src/AlgebraicCore/PPMonoid.C, src/AlgebraicCore/SparsePolyOps-RingElem.C, src/AlgebraicCore/SparsePolyOps-ideal.C, src/AlgebraicCore/SparsePolyOps-implicit.C, src/AlgebraicCore/error.C, src/AlgebraicCore/ideal.C
Now using CoCoA_THROW_ERROR1/2  (first batch)
=> AnnaB new error syntax

src/AlgebraicCore/QuotientModule.C, src/AlgebraicCore/RingZZ.C, src/AlgebraicCore/submodule.C
I left some RingZZImpl in the second argument to get a more detailed error message (inheritance)
=> New Error syntax - second batch

include/CoCoA/QuotientRing.H, src/AlgebraicCore/QuotientRing.C, src/AlgebraicCore/SparsePolyOps-hilbert.C, src/AlgebraicCore/SparsePolyOps-ideal-FGLM.C, src/AlgebraicCore/SugarDegree.C, src/AlgebraicCore/TmpToric.C, src/CoCoA-5/tests/ErrMesg.out
There are also some cosmetics changes
=> A few more updates to CoCoA_THROW_ERROR recovered from last summer

src/AlgebraicCore/obsolescent.C, src/CoCoA-5/CoCoALibSupplement.C
many changes in Error calls in CoCoALibSupplement.C
=> Another batch of updated Error calls

src/AlgebraicCore/SparsePolyOps-LRSDegeneracy.C, src/AlgebraicCore/SparsePolyOps-resultant.C
Reduced amount of output when verbosity is active.  Some cleaning & better args checks.  Improved the `CoCoA_THROW` macro calls
=> Reduced verbosity; minor cleaning; updated THROW macros

include/CoCoA/SparsePolyOps-RingElem.H, src/AlgebraicCore/SparsePolyOps-vector.C, src/CoCoA-5/BuiltInFunctions-CoCoALib.C, src/CoCoA-5/Parser.C
added functions interreduced_LT, NR_LT (CoCoALib+CoCoA5)  -- no manual yet
Nicer error  message for "A :-1;"
=> NR_LT, interreduced_LT, and an updated error message

examples/ex-c++-arith.C, examples/ex-c++-basic.C, examples/ex-c++-bool.C, examples/ex-c++-class.C, examples/ex-c++-fn-defn.C, examples/ex-c++-integers.C, examples/ex-c++-loop-for1.C, examples/ex-c++-loop-for2.C, examples/ex-c++-loop-while.C, examples/ex-c++-vector1.C, examples/ex-c++-vector2.C
In preparation for the COCOA School, I have reviewed some of the ex-c++-XYZ examples.
Probably we should request that participants (with little or no C++ experience) look at these examples so that they can learn/refresh some C++.
Some example contain "advanced" parts, which I have tried to mark as "ADVANCED"
All revised examples compile and run fine on my system.
=> Updated ex-c++-XYZ examples; corrected typos etc

examples/ex-ApproxPts1.C, examples/ex-BigInt3.C, examples/ex-CpuTimeLimit2.C, examples/ex-MVT-Simplicial.C, examples/ex-MVT-SqFr.C, examples/ex-MVT-edge.C, examples/ex-NumTheory2.C, examples/ex-PolyIterator2.C, examples/ex-RingElem2.C, examples/ex-RingHom4.C, examples/ex-RingTwinFloat1.C, examples/ex-RingTwinFloat2.C, examples/ex-SumBigRat.C, examples/ex-error1.C
Just a hasty update; maybe some of the `CoCoA_THROW_ERROR1` calls can be improved?  I'm too lazy currently.
=> Updated calls to CoCoA_THROW_ERROR

src/AlgebraicCore/BigIntOps.C, src/AlgebraicCore/BigRatOps.C, src/AlgebraicCore/GlobalManager.C, src/AlgebraicCore/MemPool.C, src/AlgebraicCore/NumTheory-CRT.C, src/AlgebraicCore/NumTheory-RatReconstruct.C, src/AlgebraicCore/RingFqVec.C, src/AlgebraicCore/RootBound.C, src/AlgebraicCore/SparsePolyOps-RingElem-homog.C, src/AlgebraicCore/SparsePolyOps-ideal-radical.C, src/AlgebraicCore/ring.C, src/AlgebraicCore/verbose.C, src/CoCoA-5/tests/ErrMesg.out
Compiles & tests run OK on my computer
=> Next wave of updates to CoCoA_THROW_ERROR

include/CoCoA/CpuTimeLimit.H, include/CoCoA/OpenMathXML.H, include/CoCoA/OrdvArith-OpenMP.H, include/CoCoA/OrdvArith.H, include/CoCoA/PolyRing.H, include/CoCoA/error.H, src/AlgebraicCore/ApproxPts2.C, src/AlgebraicCore/RingDenseUPolyClean.C, src/AlgebraicCore/RingExtAlg.C, src/AlgebraicCore/RingWeyl.C, src/AlgebraicCore/SparsePolyOps-cyclotomic.C, src/AlgebraicCore/TmpFactorDir/linalg/FFkernel.c
=> Eliminate some warnings; some tidying; added some "final" keywords

src/AlgebraicCore/ApproxPts.C, src/AlgebraicCore/ApproxPts2.C, src/AlgebraicCore/BigInt.C, src/AlgebraicCore/BigIntOps.C, src/AlgebraicCore/BigRat.C, src/AlgebraicCore/BigRatInterval.C, src/AlgebraicCore/BigRatOps.C, src/AlgebraicCore/CanonicalHom.C, src/AlgebraicCore/CpuTimeLimit.C, src/AlgebraicCore/DUPFp.C, src/AlgebraicCore/DenseMatrix.C, src/AlgebraicCore/DistrMPolyClean.C, src/AlgebraicCore/ExternalLibs-Frobby.C, src/AlgebraicCore/FractionField.C, src/AlgebraicCore/PolyRing-content.C, src/AlgebraicCore/PolyRing.C, src/AlgebraicCore/combinatorics.C, src/AlgebraicCore/degree.C, src/AlgebraicCore/factor-AlgExtn.C, src/AlgebraicCore/factor.C
Mindless -- I hope I didn't make too many mindless mistakes...
=> Phew!  Mindless work

src/CoCoA-5/CoCoAManual/CoCoAHelp.xml, src/CoCoA-5/packages/list.cpkg5
definition in list package, and documentation
=> added function FirstPosn

src/CoCoA-5/packages/BinRepr.cpkg5, src/CoCoA-5/packages/OperationCommunication.cpkg5, src/CoCoA-5/packages/hilop.cpkg5, src/CoCoA-5/packages/hp.cpkg5, src/CoCoA-5/packages/list.cpkg5, src/CoCoA-5/packages/misc.cpkg5, src/CoCoA-5/packages/obsolescent.cpkg5
Also enabled negative eval points in `EvaHilbertFn`
=> Updated some old errors in CoCoA-5 packages

include/CoCoA/TmpUniversalInvolutiveBasisContainer.H, src/AlgebraicCore/NumTheory-prime.C, src/AlgebraicCore/RingDistrMPolyInlFpPP.C, src/AlgebraicCore/RingDistrMPolyInlPP.C, src/AlgebraicCore/RingElemOps-CoprimeFactorBasis.C, src/AlgebraicCore/RingExtAlg.C, src/AlgebraicCore/RingWeyl.C, src/AlgebraicCore/SmallFqLogImpl.C, src/AlgebraicCore/SparsePolyOps-cyclotomic.C, src/AlgebraicCore/SparsePolyOps-ideal-points.C, src/AlgebraicCore/SparsePolyOps-ideal-radical.C, src/AlgebraicCore/SparsePolyOps-reduce.C, src/AlgebraicCore/TmpGPoly.C, src/AlgebraicCore/TmpGReductor.C, src/AlgebraicCore/TmpJBMill.C, src/AlgebraicCore/TmpLDP.C, src/AlgebraicCore/TmpMorseBetti.C, src/AlgebraicCore/TmpMorseResolution.C, src/AlgebraicCore/TmpPBMill.C, src/AlgebraicCore/TmpPartialMorseBetti.C, src/AlgebraicCore/TmpUniversalInvolutiveBasisContainer.C, src/AlgebraicCore/submodule.C, src/CoCoA-5/CoCoALibSupplement.C
We do still need to review some of the calls to `CoCoA_THROW_ERROR` (`1` or `2`).  I hope this is all.
=> Last wave of CoCoA_THROW_ERROR updates (except for NumTheory-factor

doc/Makefile
=> Corrected test for working txt2tags

src/CoCoA-5/packages/experimental.cpkg5
wdeg_mat  and  IsHomog_mat, wrt any weight matrix, may be useful for not posive gradings, or also for checking alternative gradings without changing ring.
=> added wdeg_mat  and  IsHomog_mat  (wdeg wrt any weight matrix)
